sudo: required
dist: bionic
addons:
  hosts:
    - iem-web-services.local
language: python
env:
  global:
    # allows testing to somewhat proceed without a database involved
    - NODATABASE=1
  matrix:
    - PYTHON_VERSION=3.8
before_install:
  - git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
  - . .ci_tooling/miniconda.sh

install:
  - pip install codecov

script:
  - coverage run --source=src setup.py test
  - coverage report
  - if [[ $PYTHON_VERSION == "3.8" ]]; then
    codecov -e TRAVIS_PYTHON_VERSION;
    fi
