sudo: required
dist: bionic
addons:
  hosts:
    - iem-web-services.local
language: python
env:
  global:
    - MPLLOCALFREETYPE=1
  matrix:
    - PYTHON_VERSION=3.8
before_install:
  - git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
  - . .ci_tooling/miniconda.sh

script:

